name: CD — Deploy to AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  S3_SCRIPTS_BUCKET: gp-data-lake-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'harneetbagga/globalpartners-data-pipeline'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Sync Glue scripts to S3
        run: |
          aws s3 sync glue_jobs/ s3://${{ env.S3_SCRIPTS_BUCKET }}/scripts/ \
            --exclude "*.pyc" \
            --delete

      - name: Sync Airflow DAGs to S3
        run: |
          aws s3 sync airflow_dags/ s3://${{ env.S3_SCRIPTS_BUCKET }}/dags/ \
            --exclude "*.pyc"

      - name: Notify success
        run: echo "✅ Deployed to AWS successfully"

      - name: CDK Deploy
        run: |
          npm install -g aws-cdk
          pip install aws-cdk-lib constructs
          cd infra/cdk
          cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:    us-east-1